matrix:
    include:
        - os: linux
          dist: trusty
          addons:
            mariadb: '10.1'

        - os: linux
          dist: xenial
          addons:
            mariadb: '10.1'

services:
  - mysql

script:
  - mysql -e 'SELECT version();'
  - mysql -e "SHOW VARIABLES LIKE '%query_cache%';"

